In [1]:
from pandas import Series,DataFrame

In [2]:
import pandas as pd

In [4]:
!type test.txt

1,2,3,4
5,6,7,8

In [5]:
!type Data.csv

Num,Item,Driver_Desp_Num
16,0,40
17,1,41
18,0,42
20,1,46
21,0,47
22,0,49
23,1,50
27,0,58
28,1,59
30,0,61
31,1,62
32,1,63
33,1,64
34,1,65
35,1,66
36,1,67
37,1,68
38,1,69
39,1,70
40,1,71
41,1,72
42,1,73
43,1,74
44,1,75
45,1,76
46,1,77
47,1,78
48,1,79
49,1,80
50,1,81
51,1,82
52,1,83
53,1,84
54,1,85
55,1,86
56,1,87
57,1,89
58,1,90
59,1,91
60,1,92
61,0,93
62,0,94
63,1,95
64,0,96
65,0,97

In [6]:
df = pd.read_csv('Data.csv')

In [7]:
df

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Num</th>
      <th>Item</th>
      <th>Driver_Desp_Num</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>16</td>
      <td>0</td>
      <td>40</td>
    </tr>
    <tr>
      <th>1</th>
      <td>17</td>
      <td>1</td>
      <td>41</td>
    </tr>
    <tr>
      <th>2</th>
      <td>18</td>
      <td>0</td>
      <td>42</td>
    </tr>
    <tr>
      <th>3</th>
      <td>20</td>
      <td>1</td>
      <td>46</td>
    </tr>
    <tr>
      <th>4</th>
      <td>21</td>
      <td>0</td>
      <td>47</td>
    </tr>
    <tr>
      <th>5</th>
      <td>22</td>
      <td>0</td>
      <td>49</td>
    </tr>
    <tr>
      <th>6</th>
      <td>23</td>
      <td>1</td>
      <td>50</td>
    </tr>
    <tr>
      <th>7</th>
      <td>27</td>
      <td>0</td>
      <td>58</td>
    </tr>
    <tr>
      <th>8</th>
      <td>28</td>
      <td>1</td>
      <td>59</td>
    </tr>
    <tr>
      <th>9</th>
      <td>30</td>
      <td>0</td>
      <td>61</td>
    </tr>
    <tr>
      <th>10</th>
      <td>31</td>
      <td>1</td>
      <td>62</td>
    </tr>
    <tr>
      <th>11</th>
      <td>32</td>
      <td>1</td>
      <td>63</td>
    </tr>
    <tr>
      <th>12</th>
      <td>33</td>
      <td>1</td>
      <td>64</td>
    </tr>
    <tr>
      <th>13</th>
      <td>34</td>
      <td>1</td>
      <td>65</td>
    </tr>
    <tr>
      <th>14</th>
      <td>35</td>
      <td>1</td>
      <td>66</td>
    </tr>
    <tr>
      <th>15</th>
      <td>36</td>
      <td>1</td>
      <td>67</td>
    </tr>
    <tr>
      <th>16</th>
      <td>37</td>
      <td>1</td>
      <td>68</td>
    </tr>
    <tr>
      <th>17</th>
      <td>38</td>
      <td>1</td>
      <td>69</td>
    </tr>
    <tr>
      <th>18</th>
      <td>39</td>
      <td>1</td>
      <td>70</td>
    </tr>
    <tr>
      <th>19</th>
      <td>40</td>
      <td>1</td>
      <td>71</td>
    </tr>
    <tr>
      <th>20</th>
      <td>41</td>
      <td>1</td>
      <td>72</td>
    </tr>
    <tr>
      <th>21</th>
      <td>42</td>
      <td>1</td>
      <td>73</td>
    </tr>
    <tr>
      <th>22</th>
      <td>43</td>
      <td>1</td>
      <td>74</td>
    </tr>
    <tr>
      <th>23</th>
      <td>44</td>
      <td>1</td>
      <td>75</td>
    </tr>
    <tr>
      <th>24</th>
      <td>45</td>
      <td>1</td>
      <td>76</td>
    </tr>
    <tr>
      <th>25</th>
      <td>46</td>
      <td>1</td>
      <td>77</td>
    </tr>
    <tr>
      <th>26</th>
      <td>47</td>
      <td>1</td>
      <td>78</td>
    </tr>
    <tr>
      <th>27</th>
      <td>48</td>
      <td>1</td>
      <td>79</td>
    </tr>
    <tr>
      <th>28</th>
      <td>49</td>
      <td>1</td>
      <td>80</td>
    </tr>
    <tr>
      <th>29</th>
      <td>50</td>
      <td>1</td>
      <td>81</td>
    </tr>
    <tr>
      <th>30</th>
      <td>51</td>
      <td>1</td>
      <td>82</td>
    </tr>
    <tr>
      <th>31</th>
      <td>52</td>
      <td>1</td>
      <td>83</td>
    </tr>
    <tr>
      <th>32</th>
      <td>53</td>
      <td>1</td>
      <td>84</td>
    </tr>
    <tr>
      <th>33</th>
      <td>54</td>
      <td>1</td>
      <td>85</td>
    </tr>
    <tr>
      <th>34</th>
      <td>55</td>
      <td>1</td>
      <td>86</td>
    </tr>
    <tr>
      <th>35</th>
      <td>56</td>
      <td>1</td>
      <td>87</td>
    </tr>
    <tr>
      <th>36</th>
      <td>57</td>
      <td>1</td>
      <td>89</td>
    </tr>
    <tr>
      <th>37</th>
      <td>58</td>
      <td>1</td>
      <td>90</td>
    </tr>
    <tr>
      <th>38</th>
      <td>59</td>
      <td>1</td>
      <td>91</td>
    </tr>
    <tr>
      <th>39</th>
      <td>60</td>
      <td>1</td>
      <td>92</td>
    </tr>
    <tr>
      <th>40</th>
      <td>61</td>
      <td>0</td>
      <td>93</td>
    </tr>
    <tr>
      <th>41</th>
      <td>62</td>
      <td>0</td>
      <td>94</td>
    </tr>
    <tr>
      <th>42</th>
      <td>63</td>
      <td>1</td>
      <td>95</td>
    </tr>
    <tr>
      <th>43</th>
      <td>64</td>
      <td>0</td>
      <td>96</td>
    </tr>
    <tr>
      <th>44</th>
      <td>65</td>
      <td>0</td>
      <td>97</td>
    </tr>
  </tbody>
</table>
</div>

In [8]:
pd.read_table('Data.csv',sep=',')

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Num</th>
      <th>Item</th>
      <th>Driver_Desp_Num</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>16</td>
      <td>0</td>
      <td>40</td>
    </tr>
    <tr>
      <th>1</th>
      <td>17</td>
      <td>1</td>
      <td>41</td>
    </tr>
    <tr>
      <th>2</th>
      <td>18</td>
      <td>0</td>
      <td>42</td>
    </tr>
    <tr>
      <th>3</th>
      <td>20</td>
      <td>1</td>
      <td>46</td>
    </tr>
    <tr>
      <th>4</th>
      <td>21</td>
      <td>0</td>
      <td>47</td>
    </tr>
    <tr>
      <th>5</th>
      <td>22</td>
      <td>0</td>
      <td>49</td>
    </tr>
    <tr>
      <th>6</th>
      <td>23</td>
      <td>1</td>
      <td>50</td>
    </tr>
    <tr>
      <th>7</th>
      <td>27</td>
      <td>0</td>
      <td>58</td>
    </tr>
    <tr>
      <th>8</th>
      <td>28</td>
      <td>1</td>
      <td>59</td>
    </tr>
    <tr>
      <th>9</th>
      <td>30</td>
      <td>0</td>
      <td>61</td>
    </tr>
    <tr>
      <th>10</th>
      <td>31</td>
      <td>1</td>
      <td>62</td>
    </tr>
    <tr>
      <th>11</th>
      <td>32</td>
      <td>1</td>
      <td>63</td>
    </tr>
    <tr>
      <th>12</th>
      <td>33</td>
      <td>1</td>
      <td>64</td>
    </tr>
    <tr>
      <th>13</th>
      <td>34</td>
      <td>1</td>
      <td>65</td>
    </tr>
    <tr>
      <th>14</th>
      <td>35</td>
      <td>1</td>
      <td>66</td>
    </tr>
    <tr>
      <th>15</th>
      <td>36</td>
      <td>1</td>
      <td>67</td>
    </tr>
    <tr>
      <th>16</th>
      <td>37</td>
      <td>1</td>
      <td>68</td>
    </tr>
    <tr>
      <th>17</th>
      <td>38</td>
      <td>1</td>
      <td>69</td>
    </tr>
    <tr>
      <th>18</th>
      <td>39</td>
      <td>1</td>
      <td>70</td>
    </tr>
    <tr>
      <th>19</th>
      <td>40</td>
      <td>1</td>
      <td>71</td>
    </tr>
    <tr>
      <th>20</th>
      <td>41</td>
      <td>1</td>
      <td>72</td>
    </tr>
    <tr>
      <th>21</th>
      <td>42</td>
      <td>1</td>
      <td>73</td>
    </tr>
    <tr>
      <th>22</th>
      <td>43</td>
      <td>1</td>
      <td>74</td>
    </tr>
    <tr>
      <th>23</th>
      <td>44</td>
      <td>1</td>
      <td>75</td>
    </tr>
    <tr>
      <th>24</th>
      <td>45</td>
      <td>1</td>
      <td>76</td>
    </tr>
    <tr>
      <th>25</th>
      <td>46</td>
      <td>1</td>
      <td>77</td>
    </tr>
    <tr>
      <th>26</th>
      <td>47</td>
      <td>1</td>
      <td>78</td>
    </tr>
    <tr>
      <th>27</th>
      <td>48</td>
      <td>1</td>
      <td>79</td>
    </tr>
    <tr>
      <th>28</th>
      <td>49</td>
      <td>1</td>
      <td>80</td>
    </tr>
    <tr>
      <th>29</th>
      <td>50</td>
      <td>1</td>
      <td>81</td>
    </tr>
    <tr>
      <th>30</th>
      <td>51</td>
      <td>1</td>
      <td>82</td>
    </tr>
    <tr>
      <th>31</th>
      <td>52</td>
      <td>1</td>
      <td>83</td>
    </tr>
    <tr>
      <th>32</th>
      <td>53</td>
      <td>1</td>
      <td>84</td>
    </tr>
    <tr>
      <th>33</th>
      <td>54</td>
      <td>1</td>
      <td>85</td>
    </tr>
    <tr>
      <th>34</th>
      <td>55</td>
      <td>1</td>
      <td>86</td>
    </tr>
    <tr>
      <th>35</th>
      <td>56</td>
      <td>1</td>
      <td>87</td>
    </tr>
    <tr>
      <th>36</th>
      <td>57</td>
      <td>1</td>
      <td>89</td>
    </tr>
    <tr>
      <th>37</th>
      <td>58</td>
      <td>1</td>
      <td>90</td>
    </tr>
    <tr>
      <th>38</th>
      <td>59</td>
      <td>1</td>
      <td>91</td>
    </tr>
    <tr>
      <th>39</th>
      <td>60</td>
      <td>1</td>
      <td>92</td>
    </tr>
    <tr>
      <th>40</th>
      <td>61</td>
      <td>0</td>
      <td>93</td>
    </tr>
    <tr>
      <th>41</th>
      <td>62</td>
      <td>0</td>
      <td>94</td>
    </tr>
    <tr>
      <th>42</th>
      <td>63</td>
      <td>1</td>
      <td>95</td>
    </tr>
    <tr>
      <th>43</th>
      <td>64</td>
      <td>0</td>
      <td>96</td>
    </tr>
    <tr>
      <th>44</th>
      <td>65</td>
      <td>0</td>
      <td>97</td>
    </tr>
  </tbody>
</table>
</div>

In [9]:
pd.read_csv('Data.csv',header=None)

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Num</td>
      <td>Item</td>
      <td>Driver_Desp_Num</td>
    </tr>
    <tr>
      <th>1</th>
      <td>16</td>
      <td>0</td>
      <td>40</td>
    </tr>
    <tr>
      <th>2</th>
      <td>17</td>
      <td>1</td>
      <td>41</td>
    </tr>
    <tr>
      <th>3</th>
      <td>18</td>
      <td>0</td>
      <td>42</td>
    </tr>
    <tr>
      <th>4</th>
      <td>20</td>
      <td>1</td>
      <td>46</td>
    </tr>
    <tr>
      <th>5</th>
      <td>21</td>
      <td>0</td>
      <td>47</td>
    </tr>
    <tr>
      <th>6</th>
      <td>22</td>
      <td>0</td>
      <td>49</td>
    </tr>
    <tr>
      <th>7</th>
      <td>23</td>
      <td>1</td>
      <td>50</td>
    </tr>
    <tr>
      <th>8</th>
      <td>27</td>
      <td>0</td>
      <td>58</td>
    </tr>
    <tr>
      <th>9</th>
      <td>28</td>
      <td>1</td>
      <td>59</td>
    </tr>
    <tr>
      <th>10</th>
      <td>30</td>
      <td>0</td>
      <td>61</td>
    </tr>
    <tr>
      <th>11</th>
      <td>31</td>
      <td>1</td>
      <td>62</td>
    </tr>
    <tr>
      <th>12</th>
      <td>32</td>
      <td>1</td>
      <td>63</td>
    </tr>
    <tr>
      <th>13</th>
      <td>33</td>
      <td>1</td>
      <td>64</td>
    </tr>
    <tr>
      <th>14</th>
      <td>34</td>
      <td>1</td>
      <td>65</td>
    </tr>
    <tr>
      <th>15</th>
      <td>35</td>
      <td>1</td>
      <td>66</td>
    </tr>
    <tr>
      <th>16</th>
      <td>36</td>
      <td>1</td>
      <td>67</td>
    </tr>
    <tr>
      <th>17</th>
      <td>37</td>
      <td>1</td>
      <td>68</td>
    </tr>
    <tr>
      <th>18</th>
      <td>38</td>
      <td>1</td>
      <td>69</td>
    </tr>
    <tr>
      <th>19</th>
      <td>39</td>
      <td>1</td>
      <td>70</td>
    </tr>
    <tr>
      <th>20</th>
      <td>40</td>
      <td>1</td>
      <td>71</td>
    </tr>
    <tr>
      <th>21</th>
      <td>41</td>
      <td>1</td>
      <td>72</td>
    </tr>
    <tr>
      <th>22</th>
      <td>42</td>
      <td>1</td>
      <td>73</td>
    </tr>
    <tr>
      <th>23</th>
      <td>43</td>
      <td>1</td>
      <td>74</td>
    </tr>
    <tr>
      <th>24</th>
      <td>44</td>
      <td>1</td>
      <td>75</td>
    </tr>
    <tr>
      <th>25</th>
      <td>45</td>
      <td>1</td>
      <td>76</td>
    </tr>
    <tr>
      <th>26</th>
      <td>46</td>
      <td>1</td>
      <td>77</td>
    </tr>
    <tr>
      <th>27</th>
      <td>47</td>
      <td>1</td>
      <td>78</td>
    </tr>
    <tr>
      <th>28</th>
      <td>48</td>
      <td>1</td>
      <td>79</td>
    </tr>
    <tr>
      <th>29</th>
      <td>49</td>
      <td>1</td>
      <td>80</td>
    </tr>
    <tr>
      <th>30</th>
      <td>50</td>
      <td>1</td>
      <td>81</td>
    </tr>
    <tr>
      <th>31</th>
      <td>51</td>
      <td>1</td>
      <td>82</td>
    </tr>
    <tr>
      <th>32</th>
      <td>52</td>
      <td>1</td>
      <td>83</td>
    </tr>
    <tr>
      <th>33</th>
      <td>53</td>
      <td>1</td>
      <td>84</td>
    </tr>
    <tr>
      <th>34</th>
      <td>54</td>
      <td>1</td>
      <td>85</td>
    </tr>
    <tr>
      <th>35</th>
      <td>55</td>
      <td>1</td>
      <td>86</td>
    </tr>
    <tr>
      <th>36</th>
      <td>56</td>
      <td>1</td>
      <td>87</td>
    </tr>
    <tr>
      <th>37</th>
      <td>57</td>
      <td>1</td>
      <td>89</td>
    </tr>
    <tr>
      <th>38</th>
      <td>58</td>
      <td>1</td>
      <td>90</td>
    </tr>
    <tr>
      <th>39</th>
      <td>59</td>
      <td>1</td>
      <td>91</td>
    </tr>
    <tr>
      <th>40</th>
      <td>60</td>
      <td>1</td>
      <td>92</td>
    </tr>
    <tr>
      <th>41</th>
      <td>61</td>
      <td>0</td>
      <td>93</td>
    </tr>
    <tr>
      <th>42</th>
      <td>62</td>
      <td>0</td>
      <td>94</td>
    </tr>
    <tr>
      <th>43</th>
      <td>63</td>
      <td>1</td>
      <td>95</td>
    </tr>
    <tr>
      <th>44</th>
      <td>64</td>
      <td>0</td>
      <td>96</td>
    </tr>
    <tr>
      <th>45</th>
      <td>65</td>
      <td>0</td>
      <td>97</td>
    </tr>
  </tbody>
</table>
</div>

In [25]:
pd.read_csv('Data.csv',names=['good','poor','excel'])

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>good</th>
      <th>poor</th>
      <th>excel</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Num</td>
      <td>Item</td>
      <td>Driver_Desp_Num</td>
    </tr>
    <tr>
      <th>1</th>
      <td>16</td>
      <td>0</td>
      <td>40</td>
    </tr>
    <tr>
      <th>2</th>
      <td>17</td>
      <td>1</td>
      <td>41</td>
    </tr>
    <tr>
      <th>3</th>
      <td>18</td>
      <td>0</td>
      <td>42</td>
    </tr>
    <tr>
      <th>4</th>
      <td>20</td>
      <td>1</td>
      <td>46</td>
    </tr>
    <tr>
      <th>5</th>
      <td>21</td>
      <td>0</td>
      <td>47</td>
    </tr>
    <tr>
      <th>6</th>
      <td>22</td>
      <td>0</td>
      <td>49</td>
    </tr>
    <tr>
      <th>7</th>
      <td>23</td>
      <td>1</td>
      <td>50</td>
    </tr>
    <tr>
      <th>8</th>
      <td>27</td>
      <td>0</td>
      <td>58</td>
    </tr>
    <tr>
      <th>9</th>
      <td>28</td>
      <td>1</td>
      <td>59</td>
    </tr>
    <tr>
      <th>10</th>
      <td>30</td>
      <td>0</td>
      <td>61</td>
    </tr>
    <tr>
      <th>11</th>
      <td>31</td>
      <td>1</td>
      <td>62</td>
    </tr>
    <tr>
      <th>12</th>
      <td>32</td>
      <td>1</td>
      <td>63</td>
    </tr>
    <tr>
      <th>13</th>
      <td>33</td>
      <td>1</td>
      <td>64</td>
    </tr>
    <tr>
      <th>14</th>
      <td>34</td>
      <td>1</td>
      <td>65</td>
    </tr>
    <tr>
      <th>15</th>
      <td>35</td>
      <td>1</td>
      <td>66</td>
    </tr>
    <tr>
      <th>16</th>
      <td>36</td>
      <td>1</td>
      <td>67</td>
    </tr>
    <tr>
      <th>17</th>
      <td>37</td>
      <td>1</td>
      <td>68</td>
    </tr>
    <tr>
      <th>18</th>
      <td>38</td>
      <td>1</td>
      <td>69</td>
    </tr>
    <tr>
      <th>19</th>
      <td>39</td>
      <td>1</td>
      <td>70</td>
    </tr>
    <tr>
      <th>20</th>
      <td>40</td>
      <td>1</td>
      <td>71</td>
    </tr>
    <tr>
      <th>21</th>
      <td>41</td>
      <td>1</td>
      <td>72</td>
    </tr>
    <tr>
      <th>22</th>
      <td>42</td>
      <td>1</td>
      <td>73</td>
    </tr>
    <tr>
      <th>23</th>
      <td>43</td>
      <td>1</td>
      <td>74</td>
    </tr>
    <tr>
      <th>24</th>
      <td>44</td>
      <td>1</td>
      <td>75</td>
    </tr>
    <tr>
      <th>25</th>
      <td>45</td>
      <td>1</td>
      <td>76</td>
    </tr>
    <tr>
      <th>26</th>
      <td>46</td>
      <td>1</td>
      <td>77</td>
    </tr>
    <tr>
      <th>27</th>
      <td>47</td>
      <td>1</td>
      <td>78</td>
    </tr>
    <tr>
      <th>28</th>
      <td>48</td>
      <td>1</td>
      <td>79</td>
    </tr>
    <tr>
      <th>29</th>
      <td>49</td>
      <td>1</td>
      <td>80</td>
    </tr>
    <tr>
      <th>30</th>
      <td>50</td>
      <td>1</td>
      <td>81</td>
    </tr>
    <tr>
      <th>31</th>
      <td>51</td>
      <td>1</td>
      <td>82</td>
    </tr>
    <tr>
      <th>32</th>
      <td>52</td>
      <td>1</td>
      <td>83</td>
    </tr>
    <tr>
      <th>33</th>
      <td>53</td>
      <td>1</td>
      <td>84</td>
    </tr>
    <tr>
      <th>34</th>
      <td>54</td>
      <td>1</td>
      <td>85</td>
    </tr>
    <tr>
      <th>35</th>
      <td>55</td>
      <td>1</td>
      <td>86</td>
    </tr>
    <tr>
      <th>36</th>
      <td>56</td>
      <td>1</td>
      <td>87</td>
    </tr>
    <tr>
      <th>37</th>
      <td>57</td>
      <td>1</td>
      <td>89</td>
    </tr>
    <tr>
      <th>38</th>
      <td>58</td>
      <td>1</td>
      <td>90</td>
    </tr>
    <tr>
      <th>39</th>
      <td>59</td>
      <td>1</td>
      <td>91</td>
    </tr>
    <tr>
      <th>40</th>
      <td>60</td>
      <td>1</td>
      <td>92</td>
    </tr>
    <tr>
      <th>41</th>
      <td>61</td>
      <td>0</td>
      <td>93</td>
    </tr>
    <tr>
      <th>42</th>
      <td>62</td>
      <td>0</td>
      <td>94</td>
    </tr>
    <tr>
      <th>43</th>
      <td>63</td>
      <td>1</td>
      <td>95</td>
    </tr>
    <tr>
      <th>44</th>
      <td>64</td>
      <td>0</td>
      <td>96</td>
    </tr>
    <tr>
      <th>45</th>
      <td>65</td>
      <td>0</td>
      <td>97</td>
    </tr>
  </tbody>
</table>
</div>

In [26]:
pd.read_csv('Data.csv',nrows=10)

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Num</th>
      <th>Item</th>
      <th>Driver_Desp_Num</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>16</td>
      <td>0</td>
      <td>40</td>
    </tr>
    <tr>
      <th>1</th>
      <td>17</td>
      <td>1</td>
      <td>41</td>
    </tr>
    <tr>
      <th>2</th>
      <td>18</td>
      <td>0</td>
      <td>42</td>
    </tr>
    <tr>
      <th>3</th>
      <td>20</td>
      <td>1</td>
      <td>46</td>
    </tr>
    <tr>
      <th>4</th>
      <td>21</td>
      <td>0</td>
      <td>47</td>
    </tr>
    <tr>
      <th>5</th>
      <td>22</td>
      <td>0</td>
      <td>49</td>
    </tr>
    <tr>
      <th>6</th>
      <td>23</td>
      <td>1</td>
      <td>50</td>
    </tr>
    <tr>
      <th>7</th>
      <td>27</td>
      <td>0</td>
      <td>58</td>
    </tr>
    <tr>
      <th>8</th>
      <td>28</td>
      <td>1</td>
      <td>59</td>
    </tr>
    <tr>
      <th>9</th>
      <td>30</td>
      <td>0</td>
      <td>61</td>
    </tr>
  </tbody>
</table>
</div>

In [27]:
df = pd.read_csv('Data.csv',chunksize=20)

In [28]:
df

In [29]:
tot= Series([])

In [32]:
for piece in df:
    tot=tot.add(piece['Num'].value_counts(),fill_value=0)

D:\python3.4\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: order is deprecated, use sort_values(...)
  if __name__ == '__main__':

In [36]:
tot

64    1.0
65    1.0
61    1.0
62    1.0
63    1.0
dtype: float64

In [37]:
import  csv

In [38]:
f = open('Data.csv')

In [39]:
f

In [40]:
print(f)

<_io.TextIOWrapper name='Data.csv' mode='r' encoding='cp936'>

In [42]:
f = open('Data.csv')

In [43]:
reader = csv.reader(f)

In [44]:
reader

In [46]:
for line in reader:
    print (line)

['Num', 'Item', 'Driver_Desp_Num']
['16', '0', '40']
['17', '1', '41']
['18', '0', '42']
['20', '1', '46']
['21', '0', '47']
['22', '0', '49']
['23', '1', '50']
['27', '0', '58']
['28', '1', '59']
['30', '0', '61']
['31', '1', '62']
['32', '1', '63']
['33', '1', '64']
['34', '1', '65']
['35', '1', '66']
['36', '1', '67']
['37', '1', '68']
['38', '1', '69']
['39', '1', '70']
['40', '1', '71']
['41', '1', '72']
['42', '1', '73']
['43', '1', '74']
['44', '1', '75']
['45', '1', '76']
['46', '1', '77']
['47', '1', '78']
['48', '1', '79']
['49', '1', '80']
['50', '1', '81']
['51', '1', '82']
['52', '1', '83']
['53', '1', '84']
['54', '1', '85']
['55', '1', '86']
['56', '1', '87']
['57', '1', '89']
['58', '1', '90']
['59', '1', '91']
['60', '1', '92']
['61', '0', '93']
['62', '0', '94']
['63', '1', '95']
['64', '0', '96']
['65', '0', '97']

In [48]:
lines = list(csv.reader(open('Data.csv')))

In [49]:
header,valuse = lines[0],lines[1]

In [50]:
data_dict  = {h:v for h,v in zip(header,zip(*valuse))}

In [51]:
data_dict

{'Num': ('1', '0', '4')}

In [58]:
with open('Data.csv','w') as f:
    writer = csv.writer(f)
    writer.writerow(('one','two','three'))
    writer.writerow(('1','2','3'))

In [56]:
writer

In [59]:
obj = """{"name":"wes","place_lived":['United States','Spain','Germen'],"pet":null,"sibling":[{"name":"Scott","age":25,"pet":"zuro"},{}]}"""

In [60]:
import json

In [61]:
result = json.loads(obj)

JSONDecodeError: Expecting value: line 1 column 30 (char 29)

In [62]:
from lxml.html import parse

In [64]:
from urllib2 import requests

ModuleNotFoundError: No module named 'urllib2'